title: Podcasterei
email: stefan.haslinger@informatom.com
description: Das Podcasting Meetup Österreich
baseurl: ""
url: "https://www.podcasterei.at"
twitter_username: podcasterei
github_username:  podcasterei

# Build settings
markdown: kramdown
monthly_archive:
  path: "archiv"

collections:
  meetups:
    output: true
  people:
    output: true

defaults:
  - scope:
      type: people
    values:
      layout: person

# disqus_shortname: podcasterei
# disqus_developer: 0 # 1 / 0
